services:
  task-app:
    image: 'currantino/task-app:0.0.1-SNAPSHOT'
    build: .
    depends_on:
      - task-app-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://task-app-postgres:5432/postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '8080:8080'

  task-app-postgres:
    image: 'postgres:15'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=postgres'
    expose:
      - 5432
