version: "3.9"

services:
  task-app:
    image: 'currantino/task-app:0.0.1-SNAPSHOT'
    build: .
    depends_on:
      - task-app-postgres
      - task-app-redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://task-app-postgres:5432/postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      REDIS_HOST: task-app-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: password
    ports:
      - '8080:8080'


  task-app-postgres:
    image: 'postgres:15'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    #TODO: Add volume
    expose:
      - 5432

  task-app-redis:
    image: 'redis:7'
    command: 'redis-server /etc/redis/redis.conf'
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    expose:
      - 6379

